name: Windows EXE Build (32-bit)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 📥 Клонируем репозиторий
        uses: actions/checkout@v3

      - name: 🔧 Устанавливаем Scoop и 32-битный MinGW
        run: |
          irm get.scoop.sh | iex
          scoop install mingw
          echo "C:\Users\runneradmin\scoop\shims" >> $GITHUB_PATH

      - name: 🔍 Проверяем установленный компилятор
        run: |
          gcc --version

      - name: 🛠️ Компилируем 32-битный EXE
        run: |
          gcc build/main.cpp -o Mayakovsky-32.exe -static -mconsole -m32
          ls -lah

      - name: 📤 Загружаем 32-битный EXE
        uses: actions/upload-artifact@v4
        with:
          name: Mayakovsky-32
          path: Mayakovsky-32.exe
