name: Windows EXE Build (32-bit)

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 📥 Клонируем репозиторий
        uses: actions/checkout@v3

      - name: 🔧 Устанавливаем 32-битный MinGW
        run: |
          choco install mingw --forcex86 -y
          echo "C:\ProgramData\chocolatey\bin" >> $GITHUB_PATH

      - name: 🛠️ Компилируем 32-битный EXE
        run: |
          g++ build/main.cpp -o Mayakovsky-32.exe -static -mconsole -m32

      - name: 📤 Загружаем 32-битный EXE
        uses: actions/upload-artifact@v4
        with:
          name: Mayakovsky-32
          path: Mayakovsky-32.exe
